### ISSUE TITLE
User experience improvments

### ISSUE THREAD

**Issue by lustremedia** [esphen/RESTED#10]
Good start but:

There are still many issues with the interface. It is not as intuitive as it could be. 

For starters:
- When clicking on a saved request I would like this request to run without needing to press "send request" again. 1 click saver.
- Creating a new request is really hidden. There should be a new request button outside of the 'save or update request' + button since it does not make sense to put a new button there.

I would use the + to spawn a new request template and use a save button for the update/save actions

These are two simple things that would enhance this rest client to a great extend.

cheers LM

**Comment by esphen** [comment]
Hi,

Thanks for the feedback. These are all great improvements, and I'll definitely try to get it into the next version. Not sure when I'll get time to work on it, but I'll put it in the 0.7 milestone for now.

Thanks for using RESTED!

**Comment by lustremedia** [comment]
Hi, I think it would be even better if one could specify if a saved rest query should be triggered on click, right now I have one query that directly pushes a tweet to twitter, and I would not want that to happen every time I open the saved query, so it should be optional I guess.

**Comment by esphen** [comment]
I was thinking a double-click could send the request, that would please both crowds I guess.

**Comment by lustremedia** [comment]
Web and double click? Not such a great idea I think! Maybe have a "checkbox" on the request that toggles  "trigger request on open". If you do that you can finegrain your api calls in that respect.

I am quite new to Angular but I always wanted to start learning it, I might jump in and help out with RESTED :-) in the near future when I find some time

**Comment by esphen** [comment]
You think so? I don't disagree, just interested in your position. It is doable with `if(active) foo()`, and could be a toggleable setting in options.

Yes, by all means, feel free to contribute! Some help around here would sure be nice, I am quite busy with work lately. Feel free to email me on rested [a] henriksen.is if you have any questions :)

**Comment by esphen** [comment]
A lot of user interface improvements are coming in 2.0, incuding some of these. Thanks for the suggestions
