### ISSUE TITLE
GET requests use hidden non-empty body

### ISSUE THREAD

**Issue by sabi0** [esphen/RESTED#101]
I sent some POST requests with non-empty body.
Then I switched method to GET (without clearing the Request body input). And when I try to send the request I get
"An error occured while fetching the resource: TypeError: HEAD or GET Request cannot have a body."

Body should be ignored for GET and HEAD requests, even if it's not empty. Especially because it is not displayed.

P.S. There's a typo in "occurred".

**Comment by sabi0** [comment]
Apparently it has been reported a week ago - #96.
Sorry for the duplicate.

(At least there is a minor addition about the typo :-) )

**Comment by esphen** [comment]
Thanks for the report - this will be fixed in the next bugfix release
