### ISSUE TITLE
Not showing all response headers

### ISSUE THREAD

**Issue by moderndeveloperllc** [esphen/RESTED#104]
Using 2.0.4, and I'm not getting all the response headers like in the 1.x versions. 

What I'm getting:
```
content-type: application/json
```

What should be shown:
```
authorization:Bearer  [Long JWT here]
content-length:114
content-type:application/json
date:Wed, 12 Jul 2017 15:15:42 GMT
server:Apache/2.4.26 (Unix) OpenSSL/1.0.2l PHP/7.1.6
status:200
strict-transport-security:max-age=31536000; includeSubDomains
x-powered-by:PHP/7.1.6
```

Am I missing a flag that should be set? 

FYI, I'm sending two headers in the GET request:
```
content-type:application/json
authorization:Bearer  [Long JWT here]
```

**Comment by esphen** [comment]
Can't reproduce. I set up an express server and sent the headers you mentioned, the headers all come through. Are you doing any sort of redirects or anything out of the ordinary? Look in the developer tools under network and see if you see anything suspicious

![screen shot 2017-07-12 at 18 12 38](https://user-images.githubusercontent.com/5845924/28127688-b6602410-672d-11e7-9783-5e29b0f4821a.png)

**Comment by esphen** [comment]
Aha, I see. I tested in Firefox - it works there. I can reproduce the issue in chrome.

Thanks, I'll look into it.

**Comment by moderndeveloperllc** [comment]
Works fine on FF 54 (macOS) here too. Hopefully it's not an AngularJS issue.

**Comment by esphen** [comment]
It's worse.. It's CORS. Turns out the `fetch` API in Chrome blocks headers that are not known, even though we are in a WebExtension context here. Firefox does not.

https://fetch.spec.whatwg.org/#http-access-control-allow-headers

 Guess I need to think about a different architecture.

**Comment by esphen** [comment]
Looks like we can use the webextension `webRequest` API to hook into the `fetch` and get the headers directly from the browser. This could be a boon for the extension at large, because this may mean we can expose things I previously though impossible, like redirect chains and such.

Will take some time to get this new stuff sorted, so don't hold your horses. I'll prioritize this for 2.1 - headers are kinda important after all..

In the mean time you can either go back to 1.x, use Firefox or set the following header in your server with a CSV of the headers you want to expose to chrome (i know, it sucks).

```http
Access-Control-Expose-Headers: foo, bar, baz
```

**Comment by moderndeveloperllc** [comment]
I'm running the server local, so I just went ahead and added the headers I really care about. Nice to see that there is a workaround on your end. Do you have a 2.1 TODO issue that I can follow? Would be useful for those of us who might be interested in helping test.

**Comment by esphen** [comment]
Awesome, good to hear. Testers would be greatly appreciated, anything I can do to help, just holler.

[The 2.1 milestone is here](https://github.com/esphen/RESTED/milestone/16), that's the closest I have to a TODO issue thus far.

When it's closer to release I'll open a PR, you can comment your findings to that. I'll also make some Release Candidates with the extension attached. That should make it easy enough for you to test it.
