### ISSUE TITLE
Fonctionnement

### ISSUE THREAD

**Issue by ltphen** [esphen/RESTED#107]
Good evening ... 
i have some trouble concerning the rested programs ... 
first i'm not very strong ...
sorry for my bad english
i just want to known how it work because with normal ajax on my server i get some CORS problem , 403 forbidden but never with rested ... how is it possible ...

Cordially 
Ltphen

**Comment by esphen** [comment]
RESTED does not have CORS problems because it is an browser extension. Web pages have CORS because of security, but in a WebExtension context, we are able to ask for permission to access all URLs at install-time. Thus you will only have CORS issues in web pages
