### ISSUE TITLE
HTTP HEAD Results are cached

### ISSUE THREAD

**Issue by dcg-csc** [esphen/RESTED#118]
RESTED Firefox plugin 2.1.1

For HTTP HEAD type requests, only the first request actually occurs.  Repeating the same request only returns the Firefox cached results. This is problematic for testing REST APIs that should return different results/headers for multiple identical requests.  I've only tried HEAD but this probably applies to other "read" request types. This is also a common problem I have seen across multiple REST plugins for Firefox.

Symptoms include the returned Date: header never changing, etc. 

Only workaround I know of is to mangle the URL arguments (?foo=bar)  each time to force a new request since it is a "new" URL which isn't a clean approach for working with REST APIs.

To always get "real" responses, the plugin should avoid Firefox response caching.

This seems to be avoided by HTTPS (probably due to Firefox policies to not cache HTTPS responses) but this doesn't help with HTTP only REST servers.

**Comment by esphen** [comment]
Hi dcg-csc,

Thanks for the detailed bug report. I agree that that this is problematic and does warrant a fix.

The Fetch API has an option called `cache` which might address this. According to the spec, when it is set to `reload`:

> Fetch behaves as if there is no HTTP cache on the way to the network. Ergo, it creates a normal request and updates the HTTP cache with the response.

This can be implemented in RESTED to ignore caches. There are, however, legitimate uses for caches in RESTED, namely testing the caching logic. I'll therefore implement this as an option, i.e. "Ignore cache, yes/no" in the options panel.

**Comment by dcg-csc** [comment]
Sounds like a great approach. Thanks for looking into the issue.

**Comment by esphen** [comment]
Added. Will be a part of the 2.2.0 release.

Thanks for the suggestion!
