### ISSUE TITLE
Feature request: JSON view of the responce

### ISSUE THREAD

**Issue by piddubnyi** [esphen/RESTED#14]
Hi Espen,
I started to use RESTED, but I hardly need json formatting of the response.
Will contribute if I find time for that, thanks.
BTW - plugin still do not appear anywhere in FF 37.0.2 on windows, the only way to access it is URL how you mentioned in my review comment.

**Comment by esphen** [comment]
Hi,

Thanks for the interest. Very strange that the button does not appear. I'll see if I can reproduce and fix at some point.

As for the JSON formatting: Provided the server sends the correct response headers (example Content-Type: application/json) the response should be json formatted. Have a look into whether the service you are using sends the correct headers.

![screenshot from 2016-01-10 18-26-55](https://cloud.githubusercontent.com/assets/5845924/12222855/d13020e0-b7c7-11e5-952f-43d145eacea4.png)
