### ISSUE TITLE
Persistent popup error if indexeddb is disabled

### ISSUE THREAD

**Issue by wohali** [esphen/RESTED#15]
As a pointer: http://stackoverflow.com/questions/28537679/check-the-real-availability-of-indexeddb-in-firefox

Your client should be able to work correctly without IndexedDB. It'd be nice not to have to dismiss the error reporting popup everytime I load it.

**Comment by esphen** [comment]
Hey,

I've addressed this now, and will have a new version available as soon as I have had a look into some other issues with RESTED.

Just a heads up, RESTED was never intended work without IndexedDB, so there may be an odd bug here or there. Feel free to create an issue if you see any deal-breakers. In any case, no options will be persisted, and no requests will able to be saved, as they require IndexedDB.

Thanks for the suggestion and the pointer, and thanks for using RESTED \o/.
