### ISSUE TITLE
No toolbar link

### ISSUE THREAD

**Issue by wohali** [esphen/RESTED#16]
As reported by another user on the RESTED reviews page, I received no icon for the client in the toolbar under Firefox 43.0.4. There's nothing in the toolbar Customize page for it, either.

I've had to bookmark a link to the chrome://rested/content/rested.html page in my bookmarks toolbar as a workaround.

Screenshot of customize page:
![mwsnap 2016-01-14 17_17_46](https://cloud.githubusercontent.com/assets/112292/12339392/e0a43a84-bae2-11e5-8a72-85a551525553.png)

**Comment by esphen** [comment]
Very strange indeed. I'll have a look at this next week, see if I can reproduce.

Thanks for the report.

**Comment by tsssystems** [comment]
I may have found out what's going on here. It seems that the icon is either under, or supplanted by, the RESTclient icon if you have that extension installed. I disabled RESTclient, and behold, the RESTED icon </> appeared in the toolbar, next to Firebug. The problem now is that the icon is only slightly darker gray than the gray of the FDE toolbar itself, so I first found it when I moused over it. Only then did I actually see it, but it's very easy to miss, and on my hi-res screen, at any distance, it's virtually invisible to me.

**Comment by esphen** [comment]
I've been trying to dig into this issue for the last few days, but no luck I'm afraid. I am using the high level [ActionButton](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_action) API to place a button into the toolbar, and really, [my implementation](https://github.com/esphen/RESTED/blob/next/main.js) is as bare bones as they get. It also mirrors the examples on Mozilla's developer network, which one would think are quite solid.

What I'm trying to say is - I don't know. This feels like a bug in Firefox, or at least the extension API. I've seen other developers [have](https://github.com/EFForg/privacybadgerfirefox/issues/253) had [issues](https://github.com/gorhill/uBlock/issues/763) with toolbar buttons as well. Also, like tsssystems suggested, [some extensions](https://addons.mozilla.org/en-US/firefox/addon/rss-icon-in-url-bar/?src=api) seem to break the  RESTED button if installed before it. 

All things considered, tweaking my high-level ActionButton API implementation just isn't doing anything, so not sure where to go from here. I'll ask around on the #extdev mozilla IRC channel next week - maybe someone knows.

My only suggestions so far are to restart the browser (and maybe [reset it](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) as well), and if that doesn't work, switch off all other extensions, and then back on one-by-one until you find one that may be a bad citizen.

I'm putting the "Help wanted" tag on this and encouraging other people to have a look at solutions or workarounds.

**Comment by Zxurian** [comment]
adding as I'm experiencing the same issue. Running Firefox 43.0.4, went to Addons, installed RESTED 0.7.1, and no icons added to addressbar / toolbar, nor does any icon show up under Customize.

**Comment by esphen** [comment]
Closing this as this was a very long time ago and probably a Firefox bug. Feel free to reopen if this happens again
