### ISSUE TITLE
React rewrite

### ISSUE THREAD

**Issue by esphen** [esphen/RESTED#17]
I'm thinking about a [React.js](https://facebook.github.io/react/) rewrite. I feel this kind of small application would be ideally suited for a [flux](https://facebook.github.io/react/blog/2014/05/06/flux.html) data flow model with a central store based around [redux](https://github.com/rackt/react-redux).

This way it would be a lot easier to handle state across the app (Active request, request list, collections). It would also be easier to make smaller, more focused components than Angular directives allow.

If implemented with [Webpack](https://github.com/webpack/webpack), it would also allow us to write ES6 with modules and support way old browsers at the same time. And as we know, new things are fun!

If this comes to fruition, it should be done on an isolated branch, and from the bottom up.

---

**The following features need to be reimplemented**
- [x] Request sending
- [x] Response preview
- [x] Collections
  - [x] Drag & Drop
  - [x] Create collections
  - [x] Add requests to collections
  - [x] Edit collection names
  - [x] Edit requests
- [x] Minimize + snazzy animation
- [x] Request history
- [x] Options
- [x] Sync storage
- [x] Import + Export
- [x] Themes
- [x] Add a migration scheme for 1.0 -> 2.0

**Comment by esphen** [comment]
Mozilla will no longer allow any submissions of Angular 1.X after October 1. according to the latest review feedback I got. This means unless the entire application is rewritten from scratch, there will only be new versions released for Chrome and Opera.....

**Comment by esphen** [comment]
Related discussion 1: https://news.ycombinator.com/item?id=12754199
Related discussion 2: https://github.com/mozilla/addons-linter/issues/1000

**Comment by Splaktar** [comment]
Angular team is working on a fix and provided more information that this vulnerability isn't specific to AngularJS: https://github.com/mozilla/addons-linter/issues/1000#issuecomment-255269186

**Comment by Splaktar** [comment]
I just wanted to confirm that this decision was indeed reversed, but it requires the use of AngularJS 1.6+.

**Comment by cricciuto** [comment]
I wanted to take a look at the react-rewrite branch and load it on Firefox but I can't seem to get it to build.
Are the docs on how to get it up (in the README.md file) proper for Windows 10?  I don't see any errors when I do the 'yarn start'  but I don't see a rested.js in the dist directory being generated. What am I missing? Just thoughts to point me in the right direction?

**Comment by esphen** [comment]
@cricciuto: Hey, cool that you want to look at it. Yeah, it should be pretty up to date (provided you're looking at the [react-rewrite readme][rw-readme] and running from the correct branch). I just got it up and running on a fresh checkout, so it works on my machine™. I suggest you inspect the output of `yarn start` to see why webpack is not outputting a `rested.js` into the dist directory. If not, I'm on [gitter][gitter], I can help you there.

[rw-readme]: https://github.com/esphen/RESTED/tree/react-rewrite#how-to-contribute
[gitter]: https://gitter.im/RESTEDclient/Lobby
