### ISSUE TITLE
finding rested.html file

### ISSUE THREAD

**Issue by oceatoon** [esphen/RESTED#20]
Hi 
I'm on ubuntu 
great tool you made 
I would like to work directly in rested.html
where i think a kept saved collections 
where can I find it ?

**Comment by esphen** [comment]
Hi there,

Not sure what you mean. If you would like to help develop, I would more than like to help you get started.

rested.html is in [data/rested.html](https://github.com/esphen/RESTED/blob/master/data/rested.html). The main logic of fetching the collections is in [data/js/controllers/root.js](https://github.com/esphen/RESTED/blob/master/data/js/controllers/root.js).

**Comment by oceatoon** [comment]
Hi esphen 
yes why not , I have good ideas I could try to help out 
but I want to understand where is that file first ?
where is the data folder nested ?

**Comment by esphen** [comment]
That's great news. Have you worked with [angular.js](http://angularjs.org/) before? If so, it should be easy to work your way down the scopes from RootCtl.

Just have a look at the [repository](https://github.com/esphen/RESTED) here on GitHub, and click the data folder. The html is in data, and all the code is there in the different sub-folders.

**Comment by oceatoon** [comment]
nop never worked with angular but will take a look 
I would like to see where you save the collections as they are typed ? in local storage ?

**Comment by esphen** [comment]
Nope, it's stored in [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API). I've tried to make it a bit simpler than tha pure IndexedDB API, look at [data/js/services/db.js](https://github.com/esphen/RESTED/blob/master/data/js/services/db.js). It has three collections, `collections`, `variables` and `options`, and they all have get, add, set and delete.

For an example, see [data/js/services/collection.js](https://github.com/esphen/RESTED/blob/master/data/js/services/collection.js).

**Comment by esphen** [comment]
Oh, and one more thing, data structure of indexedDB is in comments in [data/js/controllers/root.js](https://github.com/esphen/RESTED/blob/master/data/js/controllers/root.js).

And if you want to inspect indexedDB using developer tools, look at my IndexedDB tips in the [README](https://github.com/esphen/RESTED#how-to-contribute).

I'll probably write a guide with all this information soon, to get it all in one place

**Comment by oceatoon** [comment]
cool thanks 
i'll check it out !

**Comment by esphen** [comment]
I wrote a small guide on how to get started, have a look at this:

https://github.com/esphen/RESTED/wiki

I'll close this issue now, if you feel like contributing and need anything else, don't hesitate to contact me on my RESTED email: *rested (at) henriksen.is*

This is a good first issue, if you want to get started with something: https://github.com/esphen/RESTED/issues/22
