### ISSUE TITLE
reusing a saved url with form data , doesn't use the data

### ISSUE THREAD

**Issue by oceatoon** [esphen/RESTED#23]
when reusing a previously saved url 
that had parameter using form data 
the save parameters aren't used 
I have to remove them and type them again for them to be concidered 
is it only me ?
on Firefox , Ubuntu 14.04

**Comment by esphen** [comment]
Hi again

I tried to reproduce this, but I could not get it to not send the parameters. Are you sure the request was saved? Do you have steps to reproduce?

**Comment by oceatoon** [comment]
yes the urls are saved 
if I close and reopen theya re all there 
just the call does'nt pass the parameters
I could show you in a screen share if you like

**Comment by esphen** [comment]
So you see the parameters on the request, but they are not sent?
Then you delete and retype them, and then they are sent?
Try sending the request to https://httpbin.org/post and see what you get back. Do you see the parameters there?

If that doesn't help, you can come on https://chat.henriksen.is, and we can see if we can work it out. I made a RESTED chat room there.

**Comment by oceatoon** [comment]
I'd rather meet you here 
https://meet.jit.si/pixelhumain
account less

**Comment by esphen** [comment]
Closing this, as this was reported before the 2.0 rewrite. Feel free to reopen if this happens again
