### ISSUE TITLE
Request history

### ISSUE THREAD

**Issue by esphen** [esphen/RESTED#24]
We would like the user to be able to see a list of the last requests he/she sent using RESTED.

This could be displayed as a tab on the left panel, and when clicked, the left panel displays a list of the most recent requests.

These should probably be stored in IndexedDB as a new table, and there should be a clear button. To avoid an infinite list, we should limit the list to something like the 20 last requests.

**Comment by pafuent** [comment]
I really would love if every request that is executed ends up stored, and the key used to update a record in the storage or to create a new one is a hash that includes HTTP Verb, URL, Headers and Body.
I think an infinite list won't be a issue. I used heavily Advanced Rest Client in Chrome (the old version not the new one) and it worked in that way and I didn't have any issue regarding the amount of requests stored.
Another feature related to this one is the ability to import and export that history.

**Comment by esphen** [comment]
Hey! Thanks for chiming in.

This is probably next on the TODO list for RESTED. Request history is something I have been wanting to do for some time.

However, I am going to focus my efforts on my new project, [wsta](https://github.com/esphen/wsta), next week, and the week after that I am going on a three week holiday. So RESTED is not getting any love for at least a little while. Unfortunately I'm just one guy with two hands :)

If you want, you can have a go at implementing it yourself. I will happily merge it if it looks and works well. It should not be that hard, one would just need to add the requests to a new collection in the database every time one is sent, and then show them in a list (which could be a trimmed-down copy of the collections list).

**Comment by esphen** [comment]
This is now fixed and ready for the 0.9 release
