### ISSUE TITLE
Export collections

### ISSUE THREAD

**Issue by esphen** [esphen/RESTED#25]
We would like the user to be able to export all his/her stored collections.

This could be implemented as a tab to the right of import in the options. When the user clicks this, they can choose to export [HAR](http://www.softwareishard.com/blog/har-12-spec/) format or convert it to postman format. See [js/services/import.js](https://github.com/esphen/RESTED/blob/master/data/js/services/import.js) for examples on how this could be implemented.

Important with unit tests here. See [tests/import.js](https://github.com/esphen/RESTED/blob/master/test/tests/import.js) for examples on how one should implement export tests.

Tricky part: How to download this as a file. Is this necessary? Should we just display the exported data in a big text box?

**Comment by E14** [comment]
Just let me drop my 2 cents...

As a first implementation, just displaying it as text would certainly be enough. However, it should provide a way to exclude / include authentication data - or leave it out by default.

Also I would _really_ like the option to export only one request as well.

Finally I believe that is the way to create a downloadable file:
http://stackoverflow.com/a/4551467/1244588 (not tested though)

**Comment by esphen** [comment]
@E14 

Thanks for chiming in!

I'm currently focusing on a different project, but will be back to RESTED soon enough. Export is in progress and almost there, just a few more kinks to work out :)

Initially I will just feature dumping all requests, but later we will see if we can make the export feature a bit smarter.
