### ISSUE TITLE
adding a description to a url

### ISSUE THREAD

**Issue by oceatoon** [esphen/RESTED#33]
we are really starting to use RESTED efficiently 
it's actually becoming an API documentation and testing tool 
I 'd like to submit a request
for a description textarea added onto any url

**Comment by esphen** [comment]
Yeah, I've been thinking about something like this too, being able to give requests a name and description. That way we could redesign the collections list in #32 to be a lot more manageable when you have many requests added by only showing method and name on one line.

**Comment by esphen** [comment]
Requests have had the ability to be named for a while now - closing this issue
