### ISSUE TITLE
No mimetype field for POST payload?

### ISSUE THREAD

**Issue by bgewehr** [esphen/RESTED#40]
For using RESTED in IBM SBT POST requests we need a mimetype coding like "application/json" which other rest clients offer as a simple field above the payload body field. 

Does RESTED have such a field or another way to achive a successful post action?

**Comment by bgewehr** [comment]
Got it: A header item "Content-Type" with the value "application/json" solves the issue.

**Comment by esphen** [comment]
Glad to hear you solved the issue :)
