### ISSUE TITLE
Adding and removing collection plus adding a new request leads to crash

### ISSUE THREAD

**Issue by thotro** [esphen/RESTED#41]
Hi there! Thx for your efforts!

I've got the following error
`"error in Collection.addRequestToCollection: ""TypeError: $rootScope.collections[collectionIndex] is undefined"`.

This occurred when having two collections **A** and **B**, removing **B**, starting from a request defined in **A** and clicking on the **+** button to add a new request.

Many thanks,
Thomas

**Comment by esphen** [comment]
Closing this as it was reported before the 2.0 rewrite. Feel free to reopen if the issue persists :)
