### ISSUE TITLE
Can't use HTTPS in URL TEMPLATE

### ISSUE THREAD

**Issue by Davilink** [esphen/RESTED#42]
WHen Trying to send a post Request (or any request) using the URL Template, the HTTPS is impossbile.

Key : URI, Value : https://127.0.0.1:447/api

Result in Network Panel : http://https//127.0.0.1:447/api/user/login

**Comment by esphen** [comment]
I see, thanks for the report. It seems the order of expanding URL/prepending missing http is wrong.

I don't have time to look into this for the time being, sorry. Until I do it should work if you take the "https://"-part out of the template.

**Comment by esphen** [comment]
Fixed, look out for 0.8.1 soon
