### ISSUE TITLE
please obscure password field in Basic Auth

### ISSUE THREAD

**Issue by bortels** [esphen/RESTED#46]
yes, the password is still there in the header, but please consider making the field type password so it is obscured by ****** to prevent shoulder-surfing.

**Comment by esphen** [comment]
Sure, definitely sounds like a good addition. I'll schedule it for the next release. I'm going on holiday soon, however, so don't expect this for at least a month.

I'll implement it  as a switch, where the default is to hide the password, but with an option to show it if toggled.

**Comment by esphen** [comment]
Done, ready for 0.9
