### ISSUE TITLE
how to do a form post?

### ISSUE THREAD

**Issue by harpreetsb** [esphen/RESTED#5]
how to do a form post?

**Comment by esphen** [comment]
Hi,

You should use the POST method, and then open the "Request body" dialogue. There you can specify what the body of the POST request should look like. If you want to mimic an HTML form, you need to use URL encoded data, have a look at [this link](https://stackoverflow.com/questions/8417224/how-to-mimic-an-html-form-submission-in-a-post-request/8430062#8430062) for an example.

Thanks for using RESTED!

**Comment by harpreetsb** [comment]
i did, but does not work
![selection_021](https://cloud.githubusercontent.com/assets/6584304/10513057/9d0a59d8-7362-11e5-9480-5e19f7a2567a.jpg)

**Comment by esphen** [comment]
Try setting a Content-Type header to application/x-www-form-urlencoded. Does that help?

**Comment by harpreetsb** [comment]
yup that works,
why don't you make a dropdown "HTML FORM","CUSTOM"?
thanks

**Comment by esphen** [comment]
Yes, that's a good idea. It should make things easier. I'll see if I get time to fit that into the next release
