### ISSUE TITLE
Saving an existing request to a different collection bugs out the UI

### ISSUE THREAD

**Issue by ghost** [esphen/RESTED#50]
I seem to have discovered a minor bug that only manifests when saving requests to a new collection. Steps to reproduce:
- Ensure you have at least two collections.
- Create a request, save it to the first collection. The request is added and will turn blue in the default style (to indicate it is selected?).
- Save the request again, but to the second collection. The request is added and the second request will now also turn blue (at this point you have two blue requests).
- Modify the request URL.
- Save it to the second collection again. Click `Overwrite` in the dialog box.
- Both the request in the first collection as well as the request in the second collection now have the newly specified URL in the overview instead of just the request in the second collection.

I think this is purely a visual or UI issue, as when you refresh the page you see that only the correct request was updated.

Thanks in advance and keep up the good work!

**Comment by esphen** [comment]
Hi, thanks for the issues you have reported.

I looked at them all, and they seem reasonable to me. Should not be too much work to implement. I'm leaving for holiday soon, however, so I will not be able to work on RESTED for about a month. Sorry about that.

If you would like to see it implemented before that time, then a PR would be very welcome :)

**Comment by Gert-dev** [comment]
No problem at all, these aren't pressing issues for me, I just thought I'd let you know so you or someone else can implement them in your own time ;-).

**Comment by esphen** [comment]
Closing this as it was reported before the 2.0 rewrite. Feel free to reopen if the issue persists :)
