### ISSUE TITLE
[bug] display wrong number on big integer at Response body

### ISSUE THREAD

**Issue by marletto** [esphen/RESTED#51]
it shows like this:
{"XX":1234567890123456700}

But the server actually returns value 1234567890123456717.
Seems the number is parsed into double first, and then convert to long.

The right way is show it as string, DO NOT TRY TO PARSE IT.

**Comment by esphen** [comment]
Interesting. Thanks for reporting.

RESTED does parse JSON responses, so that it can pretty print the response. Could be a bug there, indeed. I'll schedule this for the next relese and have a look into this when I'm back from vacation. That is in about one month's time

**Comment by esphen** [comment]
My hunch was correct, it was the pretty printing of the JSON result that was the issue here. It has now been fixed ans is ready for version 0.9
