### ISSUE TITLE
Slowing Nightly - even when not in use

### ISSUE THREAD

**Issue by Noitidart** [esphen/RESTED#57]
I get messages that it is slowing down Nightly. I open the browser and many times I don't even use Rested, but I get this prompt:

![](http://i.imgur.com/q1CJB9K.png)

**Comment by esphen** [comment]
That sounds like a nightly bug to me. Because `RESTED` is literally not doing anything in the background. This is the only code that is run on load is [this](https://github.com/esphen/RESTED/blob/master/main.js), which should not cause any slowdown.

**Comment by esphen** [comment]
Closing this as I have not really heard anything about this for a year

**Comment by Noitidart** [comment]
Makes sense, thanks.
