### ISSUE TITLE
My collections are gone!

### ISSUE THREAD

**Issue by esphen** [esphen/RESTED#62]
Yeah, sorry about that. This happened after the extension went from 0.x to 1.x, and since Mozilla does not implement any kind of semantic versioning, everyone is automatically upgraded without any questions asked.

This happened because 1.0 rewrote the extension to be a WebExtension (notice the new URL), and this means the storage of the old extension is no longer present in the new context. The backend was also changed from IndexedDB to `chrome.storage`.

If you wish to recover your old collections, it may be possible to go into the [old versions of RESTED](https://addons.mozilla.org/en-US/firefox/addon/rested/versions/) and download version 0.9.1 and see if your collections are still there. If they are, you can export your collections and import them to the new version. Because of the change of technologies, there is unfortunately no way to do automatic migration.

If you try to download an older extension and export, please comment if this worked for you.

Again, very sorry for your loss.

**Comment by antheme** [comment]
Did this, found back my 1 entry collection.
The last version doesn't work for me. Requesting an idp with a post, basic auth and some form data as request body gets a 0 reply (no reply, firebug shows nothing).
Installing 0.9.1 works as it used to.

**Comment by esphen** [comment]
@antheme Are you using NoScript?

**Comment by antheme** [comment]
Yes I do.
I deactivated it and it worked.
Thanks !

**Comment by esphen** [comment]
No problem, I've seen the issue too. That's a bug in NoScript with the new WebExtension API. I'll report a bug with them tomorrow, but it might take a while for them to acknowledge and fix it. A similar bug with the built-in JSON viewer in Firefox took ages for them to fix.
