### ISSUE TITLE
Error in firefox ...

### ISSUE THREAD

**Issue by wjuniorw** [esphen/RESTED#63]
SyntaxError: 
---
in strict mode code, functions may be declared only at top level or immediately within another function
---
this error in console of firefox:
https://docs.angularjs.org/error/$injector/unpr?p0=OptionsProvider%20%3C-%20Options%20%3C-%20RootCtl

**Comment by esphen** [comment]
Hi, thanks for reporting. A few questions:

- What were you doing when this happened? How do I reproduce?
- Did it break something? If so, what happened?
- Which version of Firefox is this?
- Are you on RESTED version 1.0?

**Comment by wjuniorw** [comment]
@esphen 
firefox ESR 45.2.0
the error occur when i open the RESTED.
RESTED 1.0.0

**Comment by esphen** [comment]
I looked into this now. See https://github.com/esphen/RESTED/issues/64#issuecomment-253256379
