### ISSUE TITLE
Empty page in Firefox when starting RESTED

### ISSUE THREAD

**Issue by andy-maier** [esphen/RESTED#64]
Hi,
I am a new user of RESTED. When I start it in Firefox using the `</>` button, I get an empty page. 

The URI shown in the FF address line is: `moz-extension://<uuid>/data/rested.html` where `<uuid>` is some UUID.

The URI shown in the Windows title when looking at the source is: `file:///home/<user>/.mozilla/firefox/av258hw5.<user>/extensions/rested@restedclient.xpi!/data/rested.html` where `<user>` is my Linux user name.

When looking at the page source in FF, there is some reasonably looking HTML, and I can also locate the `rested.html` file in the .XPI archive: `/home/<user>/.mozilla/firefox/av258hw5.<user>/extensions/rested@restedclient.xpi`.

This is with Firefox 45.4.0 on RHEL 6.8.

Are there any settings in FF that might cause this?
Is there trouble shooting information?

Andy

**Comment by esphen** [comment]
Hi, thanks for dropping by

Could you please press F12 (open developer tools) and look at the console when RESTED is open? Paste me any error messages you see.

You could try entering `chrome.storage.local.clear()` in the console

**Comment by ichhaporia** [comment]
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function options.js:26:15
"Error: [$injector:unpr] http://errors.angularjs.org/1.5.8/$injector/unpr?p0=OptionsProvider%20%3C-%20Options%20%3C-%20RootCtl
N/<@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:6:412
cb/n.$injector<@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:43:174
d@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:40:432
cb/R<@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:43:234
d@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:40:432
e@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:41:158
h/<.invoke@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:41:243
ff/this.$get</</<@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:89:434
p@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:65:128
g@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:58:481
aa/<@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:58:119
Bc/c/</<@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:21:4
vf/this.$get</m.prototype.$eval@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:145:343
vf/this.$get</m.prototype.$apply@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:146:47
Bc/c/<@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:20:486
h/<.invoke@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:41:454
Bc/c@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:20:1
Bc@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:21:179
fe@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:20:1
@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/angular.min.js:317:386
n.Callbacks/i@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/jquery.min.js:2:27060
n.Callbacks/j.fireWith@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/jquery.min.js:2:27828
.ready@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/jquery.min.js:2:29619
J@moz-extension://02a81c39-7e46-49d6-81ac-3d32366baf11/data/ext/jquery.min.js:2:29804
"

**Comment by esphen** [comment]
@ichhaporia So that is the same error as https://github.com/esphen/RESTED/issues/63, and both of you say you are using Firefox ESR 45. I'll see if I can reproduce later today.

**Comment by ichhaporia** [comment]
I updated Firefox to latest 49.0.1 and that seems to have resolved the issue — the screen is no longer blank.

**Comment by esphen** [comment]
I successfully reproduced on Firefox 45 ESR. [Since I can't actually fix the issue right now](https://github.com/esphen/RESTED/issues/17), I have increased the min. required version of 1.0 to 47 to prevent installs on 45 and 46.

To anyone stuck on lesser versions for whatever reason, you can go [here](https://addons.mozilla.org/en-US/firefox/addon/rested/versions/) to download an old version of RESTED.
