### ISSUE TITLE
Render response as html when the body is html code

### ISSUE THREAD

**Issue by mr-mmmmore** [esphen/RESTED#66]
First many thanks for this great addon, it makes testing a REST service really easy. There is one thing that could improve the experience: detecting when the response is in HTML and then render it as html, not as raw text.

I use RESTED to develop a rest service, based on Laravel. When something goes wrong, by default Laravel will display an html page. This page is displayed as raw text in RESTED, so I have to dig in the very verbose HTML to find the error message, this is not very convenient.

There are ways to force Laravel to send the error in the same format as the request (JSON), but anyway, I thought that since we're in a browser, it would be logical to render an html response as html (in the body response frame).

**Comment by esphen** [comment]
Implemented in 2.0 as a sandboxed iframe. Hopefully this satisfies the reviewers.
