### ISSUE TITLE
Show time for request processing

### ISSUE THREAD

**Issue by al-indigo** [esphen/RESTED#67]
It would be very convenient if there were an option to show time needed for request execution (really missing it). 

E.g. 200 OK (0.156s)

**Comment by esphen** [comment]
I like this idea. Thanks!
I'm currently busy rewriting RESTED to react and redux, but after that I'll have a look at this.
In the mean time, it is possible to open the developer tools (F12) and look at the request time in the network panel.

**Comment by al-indigo** [comment]
Thanks, it's just the way I do it now :) I like your project and just wanted to propose a useful enhancement
