### ISSUE TITLE
Enable sending body in request

### ISSUE THREAD

**Issue by cmeeren** [esphen/RESTED#69]
I can find no way of adding a request body. Is this possible? If not, could it be implemented?

**Comment by cmeeren** [comment]
Oh, nevermind. I saw now I can choose method "Custom", which will allow me to specify the verb manually and also shows the request body field.

**Comment by esphen** [comment]
👍

**Comment by cmeeren** [comment]
In the end, the problem was that I wanted to use a body with a GET request, which is [ill-advised](http://stackoverflow.com/a/983458/2978652).
