### ISSUE TITLE
Allow prettifying output

### ISSUE THREAD

**Issue by Gert-dev** [esphen/RESTED#71]
Hello

Syntax highlighting is automatically performed for JSON and XML output, which is great. I was wondering if it would be possible to also enable automatic prettifying of the response as most API's don't bother with this (since it's only consumed by programmatic clients anyway).

This would greatly improve readability when examining the output of an API you are unfamiliar with. Currently I usually paste the output in some sort of prettifier (but that quickly becomes cumbersome). It may be a good idea to, like syntax highlighting, limit this to responses of a certain size.

Thanks for your great work!

**Comment by esphen** [comment]
Hi Gert,

Hm, this is actually a regression in 2.0. It should format JSON, but it doesn't! Prettifying XML is a fair bit more difficult, so that's a different issue

Thanks for reporting this :)

**Comment by Gert-dev** [comment]
Thanks for your response! I'm not sure about JavaScript, but perhaps you can parse the XML into a DOM structure (possibly via a library) and then simply dump/write it again. Most implementations will already provide some sort of pretty printing for it by default, even a rudimentary or imperfect way would be a major help to readability.

Keep up the great work 👍
