### ISSUE TITLE
Ability to remove items from a collection

### ISSUE THREAD

**Issue by Gert-dev** [esphen/RESTED#72]
Hello

It could just be me looking in all the wrong places, but is it possible that there is no longer an option to remove items that were saved to a collection in 2.0.0 RC2?

**Comment by esphen** [comment]
Hi Gert.

Thanks for testing 2.0! That's much appreciated.
Yeah, it's there, it's just a bit more hidden now. Click "Toggle Edit" first to enter edit mode, then the delete button appears
