### ISSUE TITLE
Ability to update existing items in a collection

### ISSUE THREAD

**Issue by Gert-dev** [esphen/RESTED#73]
Hello

Before 2.0.0 RC2, I recall there was a dialog asking whether you wanted to override an existing request if it was already part of a collection. In 2.0.0 RC2, the request always seems to be added as a new one.

Though I must admit that the original confirmation dialog was a bit cumbersome, perhaps it would be a good idea to have two buttons: `Save` and `Save as new` when editing a request that's already saved?

Thanks in advance

**Comment by esphen** [comment]
Hi Gert.

Yeah, in 2.0 editing of requests has been changed, as I really didn't like the old solution very much. Now you no longer edit a request directly, you have to enter an "edit mode" by clicking the cog first, then you can edit and save the request. Hopefully this is more intuitive than the "Add request" menu item which both was responsible for editing and creating new requests
