### ISSUE TITLE
A custom referer header is ignored in the request

### ISSUE THREAD

**Issue by geterns** [esphen/RESTED#76]
Reproducible. Is it a bug or a feature?

**Comment by geterns** [comment]
Already set network.http.sendRefererHeader to 1 and it didn't help

**Comment by esphen** [comment]
It's a feature of the web. You can't set some headers manually, only the user agent has control over them.

https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

**Comment by geterns** [comment]
@esphen Thanks, I didn't realize that before.

**Comment by rvernica** [comment]
I'm using RESTED to debug an API. The POST requests require a Referer header. I Referer header set to the same value as the request URL or just the host is fine. If the header can't be set from RESTED, why is Firefox not setting it?
