### ISSUE TITLE
Unchecking "Use form data" doesn't send Request Body

### ISSUE THREAD

**Issue by moderndeveloperllc** [esphen/RESTED#81]
Using the Chrome Extension RC2

When sending a request body via POST (JSON in my case), my browser nor application indicates that a body is being sent at all. I put the data as form attributes, and I see those in the Inspection panel as Request payload". Additionally, even if I uncheck that box, it still send the form attributes data, not the Request Body data. i should note that 1.0.0 works great. Same data, same checkboxes checked, etc.

**Comment by esphen** [comment]
Thanks for the report. Unfortunately this issue slipped through the cracks and will be fixed shortly

**Comment by esphen** [comment]
2.0.2 submitted for review

**Comment by moderndeveloperllc** [comment]
@esphen Thanks. Your extension is by far the best tool available for testing REST APIs as far as I'm concerned. Glad to see that you are still plugging away at it.
