### ISSUE TITLE
Do not automatically follow redirects

### ISSUE THREAD

**Issue by wrprice** [esphen/RESTED#84]
I have an endpoint that responds with a 300-level redirect.  I cannot debug this endpoint in RESTED, e.g. to verify header fields, etc., because it immediately follows the redirect and displays the details for the resulting (redirected) request instead of the original.

**Comment by esphen** [comment]
This is a security feature of the web platform I'm afraid. Redirects are completely transparent from the JavaScript sandbox.

**Comment by esphen** [comment]
Turns out this is possible with the `webRequest` WebExtension API, and will be a feature released in 2.1
