### ISSUE TITLE
Version 2.0.1 is broken

### ISSUE THREAD

**Issue by Amartel1986** [esphen/RESTED#85]
Firefox 53.0.3 (64-bit)

1. Client stopped understanding 'localhost' domen. When I click 'Send Request' - nothing happens, only url is highlighted with red (wtf does this mean? why do I have to guess?). Changing 'localhost' to '127.0.0.1' fixed this, but...
2. POST ignored 'Request Body'. Completely.
3. 'Add to collection' button does nothing.
4. All changes made are discarded as soon as I switch to another request in my collection.
5. Some settings saved are not restored. For example, 'Use form data' check box is checked for request, which I saved without it.

Overall impression - "Please, undo this"! Previous version had problems with saving requests to collection, but at least it worked. New version - doesn't.

**Comment by esphen** [comment]
That's not good. If you have issues with the new version, you can get an older version from [AMO](https://addons.mozilla.org/en-US/firefox/addon/rested/versions/) until I can figure this out.

**Comment by Amartel1986** [comment]
Thanks for the link. 'cause all the other rest clients for firefox sucks. Hope you'll fix everything soon.

**Comment by esphen** [comment]
I just published 2.0.2 for review. It does the following:

 1. Client stopped understanding 'localhost' domen. When I click 'Send Request' - nothing happens, only url is highlighted with red (wtf does this mean? why do I have to guess?). Changing 'localhost' to '127.0.0.1' fixed this, but...
    - There was some overzealous validation here (required at least `foo.bar`). This validation is now removed
2. POST ignored 'Request Body'. Completely.
    - Bug, fixed
3. 'Add to collection' button does nothing.
    - Also a result of the validation
4. All changes made are discarded as soon as I switch to another request in my collection.
    - In order to edit a request in 2.0 you explicitly have to click edit on that request. Click the "cog" icon in the list, do your alterations and then save. This is to remove confusion around the "plus" button in the request and make sure it only adds new requests.
5. Some settings saved are not restored. For example, 'Use form data' check box is checked for request, which I saved without it.
    - This is a bug, but will be adressed later due to the more pressing issue of point 1 and 2

**Comment by esphen** [comment]
Closing this, as all the points except 5 have been addressed. Don't worry, I haven't forgotten about 5; it is now tracked in #88.

Thanks for the detailed report, it was immensely helpful.
