### ISSUE TITLE
Make the logo link to the addon homepage (on GitHub)

### ISSUE THREAD

**Issue by sabi0** [esphen/RESTED#86]
Or maybe add a link to GitHub at the bottom of the page.
Current;y I have to go all the way through Add-ons > Extensions > More > Homepage.

**Comment by esphen** [comment]
I think it would be annoying to have the logo go to the extension page, as I would call that unexpected behavior. However I think that a link in a very minimal "footer" is a good idea.

**Comment by esphen** [comment]
I added some links in the bottom of the application that will be a part of the next release.

Thanks for the suggestion!
