### ISSUE TITLE
Persist "use form data" on request

### ISSUE THREAD

**Issue by esphen** [esphen/RESTED#88]
This bool is persisted separately today. Thus each request today defaults to showing the form fields section, regardless of whether or not it uses form data.

This change should ensure it is persisted as an enum (e.g. `dataType: 'formData'`) to allow other presets than just form data.

See also #85.

**Comment by sabi0** [comment]
Please also persist the default state.
I never actually use form data. And I don't use presets either.
So every time I open RESTED I have to disable this checkbox to enter body content. That's quite annoying.
