### ISSUE TITLE
Cross-origin requests issue

### ISSUE THREAD

**Issue by sabi0** [esphen/RESTED#93]
When I am using RESTClient to send a POST request it is sent without any "cross-origin stuff" (I see that from the logs on the server).

But when I send the same request from RESTED it is handled as if it was sent from some web application rather than from a browser add-on (i.e. with "cross-origin", pre-flight, etc.). And then I get this on the server:

> Cross-origin request to /v1/api/... is a simple cross-origin request
> Cross-origin request to /v1/api/... with origin moz-extension://74a0e7a0-35cc-478b-955d-05aa3b20093c does not match allowed origins

Is it probably because RESTED is opened as a page at moz-extension://74a0e7a0-35cc-478b-955d-05aa3b20093c/dist/index.html while RESTClient is loaded from chrome://restclient/content/restclient.html ?

**Comment by esphen** [comment]
Yes, RESTED is a website wrapped in a webextension. However, it is allowed to ignore cross origin rules because it is running in a privileged context.

Are you experiencing any issues with this?

**Comment by sabi0** [comment]
No, I didn't notice any problems yet.
Just discovered that logging on the server about not matching allowed origins. And that triggered my suspicion.

Does it mean by the way that I won't be able to use RESTED while offline? (e.g. testing REST API on a local http server)

**Comment by esphen** [comment]
No, it absolutely works offline. All the assets and scripts are part of the extension zip file which is installed in the browser - so it will work offline. You will obviously get an error when trying to fetch resources from the internet, and collection syncing will not work, but that is all you should notice.

 Closing this, but feel free to reopen for discussion if you have any concerns.
