### ISSUE TITLE
Headers names suggestions by the first letters

### ISSUE THREAD

**Issue by sabi0** [esphen/RESTED#94]
When typing something like "CT" into the header name field I'd love to see "Content-Type" in the suggestions list.

A few more examples:
CC => Cache-Control
IMS => If-Modified-Since

**Comment by esphen** [comment]
If anyone wants to have a go at this, the code is here: https://github.com/esphen/RESTED/blob/master/src/components/Request/HeaderNameAutosuggest.js#L10-L21

**Comment by esphen** [comment]
I added a fuzzy search feature which is comparable to sublime's ctrl+p. This is similar to what you are suggesting.

Pushed on the next branch, will be part of 2.2.0. Thanks for the suggestion.
