### ISSUE TITLE
Do not suggest response headers

### ISSUE THREAD

**Issue by sabi0** [esphen/RESTED#95]
When adding a request header there is no point to suggest _response_ headers like `Access-Control-Allow-Origin`.

**Comment by esphen** [comment]
This list needs to be filtered: https://github.com/esphen/RESTED/blob/master/src/constants/commonHeaders.js

**Comment by esphen** [comment]
I took the list from [here](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Request_fields) and used that as the list of suggestions.

Pushed on the next branch, will be part of 2.2.0. Thanks for the suggestion.
