### ISSUE TITLE
Switching method to method that does not support body should clear body

### ISSUE THREAD

**Issue by esphen** [esphen/RESTED#96]
From an AMO review comment:

> It works like a charm, thank you for your great extension.
> I see only one thing to change, if you send a request body using POST/PUT and then you switch to send a DELETE, it continues to send the hidden request body from previous POST/PUT.

**Comment by VincentNikkelen** [comment]
I guess I am having a related problem, let me know if I should open a new issue.

Sending a POST with a body followed by sending a GET results in the following error message:
"An error occured while fetching the resource: TypeError: HEAD or GET Request cannot have a body."

Env:
Firefox 54 (64 bit), OS-X
Rested 2.0.3

That said, I really like you extension and hope can test it more thoroughly in the future.
